force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR-{0000000}</displayFormat>
        <label>Trade ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/BuyAmount__c.field-meta.xml
<CustomField>
    <fullName>BuyAmount__c</fullName>
    <formula>SellAmount__c * Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Buy Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/BuyCurrency__c.field-meta.xml
<CustomField>
    <fullName>BuyCurrency__c</fullName>
    <label>Buy Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/SellCurrency__c.field-meta.xml
<CustomField>
    <fullName>SellCurrency__c</fullName>
    <label>Sell Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TradeBooked__e/TradeBooked__e.object-meta.xml
<CustomObject>
    <label>TradeBooked</label>
    <pluralLabel>TradesBooked</pluralLabel>
</CustomObject>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EUR</fullName>
        <default>true</default>
        <label>EUR</label>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TradeUtility.cls
/**
 * @description       : Trade__c Object Utility Class
 * @author            : Dario
 * @group             : 
 * @last modified on  : 04-29-2022
 * @last modified by  : Dario
 * Modifications Log
 * Ver   Date         Author   Modification
 * 1.0   04-29-2022   Dario   Initial Version
**/
public class TradeUtility {
    private static String STRING_CHATTER_GROUP_NAME_TRADE_REVIEWS = 'Trade Reviews';
    
    /**
    * @description Create platform event and chatter post every time a new trade is created
    * @author Dario | 04-29-2022 
    * @param Map<Id Trade__c> mapInsertedTrades 
    **/
    public static void createRecordsAfterInsert(Map<Id, Trade__c> mapInsertedTrades){
        List<TradeBooked__e> listEvents = new List<TradeBooked__e>();
        List<FeedItem> listFeedItems = new List<FeedItem>();
        
        for(Trade__c trade : mapInsertedTrades.values()){
            listEvents.add(createEvent());
            listFeedItems.add(createFeedItem(trade));
        }
        
        Database.SaveResult[] eventSaveResults = EventBus.publish(listEvents);
        Database.SaveResult[] feedItemSaveResults = Database.insert(listFeedItems);
    }
    
    /**
    * @description Get the Chatter Group Trade Reviews ID
    * @author Dario | 04-29-2022 
    * @return List<CollaborationGroup> 
    **/
    private static List<CollaborationGroup> tradeReviewers;
    private static List<CollaborationGroup> getTradeReviewers() {
        if(tradeReviewers == null){
            tradeReviewers = [SELECT Id, Name FROM CollaborationGroup WHERE Name =: STRING_CHATTER_GROUP_NAME_TRADE_REVIEWS];
        }
        return tradeReviewers;
    }
    
    /**
    * @description Create TradeBooked__e event
    * @author Dario | 04-29-2022 
    * @return TradeBooked__e 
    **/
    private static TradeBooked__e createEvent(){
        TradeBooked__e event = new TradeBooked__e();
        return event;
    }
    
    /**
    * @description Create ChatterPost item
    * @author Dario | 04-29-2022 
    * @param Trade__c trade 
    * @return FeedItem 
    **/
    private static FeedItem createFeedItem(Trade__c trade){
        String fullFileURL = URL.getSalesforceBaseUrl().toExternalForm()+'/'+ trade.id;
        FeedItem feedItem = new FeedItem();
        feedItem.Body = 'A new trade has been created with the following data:\n'+
            'Sell Currency: '+trade.SellCurrency__c +'\n'+
            'Sell Amount: '+trade.SellAmount__c +'\n'+
            'Buy Currency: '+trade.BuyCurrency__c +'\n'+
            'Buy Amount: '+trade.BuyAmount__c +'\n'+
            'Rate: '+trade.Rate__c +'\n'+
            'Booked Date: '+trade.CreatedDate +'\n'+
            'Link to the trade: '+fullFileURL;
        feedItem.ParentId = getChatterPostParentId(trade.id);
        feedItem.Type = 'LinkPost';
        return feedItem;    
    }
    
    /**
    * @description Get the ChatterPost parentId. ChatterGroup Id if it exist, or the trade id otherwise
    * @author Dario | 04-29-2022 
    * @param Id tradeId 
    * @return Id 
    **/
    @TestVisible static private Id getChatterPostParentId(Id tradeId){
        return !getTradeReviewers().isEmpty() ? getTradeReviewers()[0].Id : tradeId;
    }
    
}